name: Michalewicz
n_tot: 500
N_init: 10
dim: 50
T: 1
lb: 0
ub: 3.14

fn:
  _target_: botorch.test_functions.synthetic.Michalewicz
  dim: ${..dim}
  negate: False  # Negate the function to turn it into a minimization problem
